name: C/C++ CI

on: push

jobs:
  build:
    name: Build project for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v1
    - name: configure && build
      run: |
        mkdir build
        cd build
        cmake ..
        exit 0
        cmake --build . -- -j
